include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - 'lib/generated_plugin_registrant.dart'

linter:
  rules:
    unnecessary_this: false
    prefer_single_quotes: true
    prefer_final_parameters: true
    always_use_package_imports: true
    always_declare_return_types: true
    lines_longer_than_80_chars: true
    use_super_parameters: true
    require_trailing_commas: true
