include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - 'lib/generated_plugin_registrant.dart'

linter:
  rules:
    prefer_single_quotes: true
    prefer_final_parameters: true
    unnecessary_this: false
