name: perthle
repository: https://github.com/Alecadabra/perthle

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ^3.0.5

dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

  flutter_neumorphic: ^3.2.0
  share_plus: ^4.0.4
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  url_launcher: ^6.0.20
  provider: ^6.0.2
  firebase_core: ^1.19.2
  firebase_auth: ^3.4.2
  firebase_app_check: ^0.0.6+18
  cloud_firestore: ^3.4.6
  dartx: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/dictionary/

  fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins-Thin.ttf
        weight: 100
        style: normal
      - asset: assets/fonts/Poppins-ThinItalic.ttf
        weight: 100
        style: italic
      - asset: assets/fonts/Poppins-ExtraLight.ttf
        weight: 200
        style: normal
      - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
        weight: 200
        style: italic
      - asset: assets/fonts/Poppins-Light.ttf
        weight: 300
        style: normal
      - asset: assets/fonts/Poppins-LightItalic.ttf
        weight: 300
        style: italic
      - asset: assets/fonts/Poppins-Regular.ttf
        weight: 400
        style: normal
      - asset: assets/fonts/Poppins-Italic.ttf
        weight: 400
        style: italic
      - asset: assets/fonts/Poppins-Medium.ttf
        weight: 500
        style: normal
      - asset: assets/fonts/Poppins-MediumItalic.ttf
        weight: 500
        style: italic
      - asset: assets/fonts/Poppins-SemiBold.ttf
        weight: 600
        style: normal
      - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
        weight: 600
        style: italic
      - asset: assets/fonts/Poppins-Bold.ttf
        weight: 700
        style: normal
      - asset: assets/fonts/Poppins-BoldItalic.ttf
        weight: 700
        style: italic
      - asset: assets/fonts/Poppins-ExtraBold.ttf
        weight: 800
        style: normal
      - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
        weight: 800
        style: italic
      - asset: assets/fonts/Poppins-Black.ttf
        weight: 900
        style: normal
      - asset: assets/fonts/Poppins-BlackItalic.ttf
        weight: 900
        style: italic
