name: prod
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@main
      with:
          flutter-version: '3.0.x'
          channel: 'stable'
    - run: flutter pub get
    - run: flutter build web
    - name: Archive Production Artifact
      uses: actions/upload-artifact@v3
      with:
        name: web-build
        path: build/web
  deploy-prod:
    name: Deploy to Prod
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: https://perthle.web.app
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: web-build
          path: build/web
      - name: Deploy to Firebase
        id: deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_HOSTING }}
          channelId: live
