name: stage
on:
  push:
    branches-ignore:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment:
      name: stage
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@main
      with:
          channel: 'stable'
    - run: flutter pub get
    - run: flutter build web
    - name: Archive Production Artifact
      uses: actions/upload-artifact@v3
      with:
        name: web-build
        path: build/web
  deploy_stage:
    name: Deploy to Stage
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: stage
      url: ${{ steps.deploy.outputs.details_url }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: web-build
          path: build/web
      - name: Deploy to Firebase
        id: deploy
        uses: FirebaseExtended/action-hosting-deploy@latest
        with:
          firebaseServiceAccount: ${{ secrets.FIREBASE_TOKEN }}
          projectId: ${GITHUB_REF##*/}
