name: stage
on: [push, pull_request_target]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Get Flutter version
      id: get-flutter-version
      uses: zgosalvez/github-actions-get-flutter-version-env@v3.0.8
    - name: Setup flutter environment
      uses: subosito/flutter-action@v2.16.0
      with:
          flutter-version: ${{ steps.get-flutter-version.outputs.version }}
          channel: 'stable'
    - run: flutter pub get
    - name: Build for stage
      run: flutter build web --dart-define=ENV=stage
    - name: Archive Production Artifact
      uses: actions/upload-artifact@v4
      with:
        name: web-build
        path: build/web
  deploy_stage:
    name: Deploy to Stage
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: stage
      url: ${{ steps.deploy.outputs.details_url }}
    if: ${{ github.event_name == 'pull_request_target' || github.actor == 'Alecadabra' }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: web-build
          path: build/web
      - name: Extract branch name
        shell: bash
        run: echo "branch_name=${GITHUB_REF#refs/heads/}" | tr / - >> $GITHUB_ENV
        id: extract_branch
      - name: Deploy to Firebase
        id: deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_HOSTING }}
          channelId: ${{ env.branch_name }}
