name: stage
on:
  push:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@main
      with:
          flutter-version: '3.7.x'
          channel: 'stable'
    - run: flutter pub get
    - run: flutter build web --dart-define=ENV=stage
    - name: Archive Production Artifact
      uses: actions/upload-artifact@v3
      with:
        name: web-build
        path: build/web
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@main
      with:
          flutter-version: '3.7.x'
          channel: 'stable'
    - run: flutter pub get
    - run: flutter test
  deploy_stage:
    name: Deploy to Stage
    needs: [build, test]
    runs-on: ubuntu-latest
    environment:
      name: stage
      url: ${{ steps.deploy.outputs.details_url }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: web-build
          path: build/web
      - name: Extract branch name
        shell: bash
        run: echo "branch_name=${GITHUB_REF#refs/heads/}" | tr / - >> $GITHUB_ENV
        id: extract_branch
      - name: Deploy to Firebase
        id: deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_HOSTING }}
          channelId: ${{ env.branch_name }}
